//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.DAL.GridMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDet
    {
        public int ProfileID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public int Gender { get; set; }
        public byte[] ItemImage { get; set; }
    }
}
